### ISSUE TITLE
Examples for CHARMM FEP

### ISSUE THREAD

**Issue by leelasd** [halx/FESetup#1]
Hi,

I was wondering is it possible to setup CHARMM Relative FEPs with FESetup ? Is there any tutorial ?

**Comment by halx** [comment]
Hi Leela,

if you are happy using the PERT module you can indeed use FESetup with CHARMM.  Just set the AFE.type to charmm/pert in the global section.  See the [manual](https://ccpforge.cse.rl.ac.uk/gf/project/ccpbiosim/wiki/?pagename=Manual).

**Comment by leelasd** [comment]
Thanks, Hannes !! Much appreciate it. It works for me
